from enum import Enum

import numpy as np
import numpy.typing as npt

class OperationCode(Enum):
    H = ...
    X = ...
    Y = ...
    Z = ...
    RX = ...
    RY = ...
    RZ = ...
    CX = ...
    CZ = ...
    SWAP = ...


class ResultMode(Enum):
    SAMPLE = ...
    EXPECTATION = ...
    STATEVECTOR = ...


class Operation:
    @property
    def name(self) -> str: ...
    @property
    def code(self) -> OperationCode: ...
    @property
    def qubits(self) -> list[int]: ...
    @property
    def parameters(self) -> list[float]: ...


class Program:
    def __init__(self, num_qubits: int) -> None: ...
    @property
    def num_qubits(self) -> int: ...
    @property
    def operations(self) -> list[Operation]: ...


class PauliZ:
    @property
    def qubit(self) -> int: ...


class Target:
    @property
    def name(self) -> str: ...
    @property
    def operations(self) -> list[OperationCode]: ...
    @property
    def result_modes(self) -> list[ResultMode]: ...
    @property
    def max_qubits(self) -> int | None: ...
    @property
    def simulator(self) -> bool: ...
    def supports_operation(self, code: OperationCode) -> bool: ...
    def supports_result(self, mode: ResultMode) -> bool: ...


class ExecutionPlan:
    @property
    def backend(self) -> str: ...
    @property
    def method(self) -> str: ...
    @property
    def exact(self) -> bool: ...
    @property
    def threads(self) -> int: ...
    @property
    def original_operations(self) -> int: ...
    @property
    def compiled_steps(self) -> int: ...
    @property
    def active_qubits(self) -> int: ...
    @property
    def estimated_state_bytes(self) -> int: ...


class StateVector:
    @property
    def values(self) -> npt.NDArray[np.complex128]: ...
    @property
    def backend(self) -> str: ...


class Samples:
    @property
    def values(self) -> npt.NDArray[np.int8]: ...
    @property
    def shots(self) -> int: ...
    @property
    def backend(self) -> str: ...
    def counts(self) -> dict[str, int]: ...


class Expectation:
    @property
    def value(self) -> float: ...
    @property
    def backend(self) -> str: ...
    @property
    def active_qubits(self) -> int: ...
    @property
    def compiled_steps(self) -> int: ...
    @property
    def estimated_state_bytes(self) -> int: ...


def h(program: Program, qubit: int) -> Program: ...
def x(program: Program, qubit: int) -> Program: ...
def y(program: Program, qubit: int) -> Program: ...
def z(program: Program, qubit: int) -> Program: ...
def rx(program: Program, angle: float, qubit: int) -> Program: ...
def ry(program: Program, angle: float, qubit: int) -> Program: ...
def rz(program: Program, angle: float, qubit: int) -> Program: ...
def cx(program: Program, control: int, target: int) -> Program: ...
def cz(program: Program, control: int, target: int) -> Program: ...
def swap(program: Program, first: int, second: int) -> Program: ...
def Z(qubit: int) -> PauliZ: ...

def native_target() -> Target: ...
def plan(
    program: Program,
    result_mode: ResultMode,
    backend: str = "auto",
) -> ExecutionPlan: ...

def expectation_plan(
    program: Program,
    observable: PauliZ,
    backend: str = "auto",
) -> ExecutionPlan: ...

def statevector(program: Program, backend: str = "auto") -> StateVector: ...
def sample(
    program: Program,
    shots: int = 1024,
    seed: int | None = None,
    backend: str = "auto",
) -> Samples: ...
def expect(
    program: Program,
    observable: PauliZ,
    backend: str = "auto",
) -> Expectation: ...

def core_language() -> str: ...
def parallel_threads() -> int: ...
