from enum import Enum

import numpy as np
import numpy.typing as npt

class OperationCode(Enum):
    H = ...
    X = ...
    Y = ...
    Z = ...
    RX = ...
    RY = ...
    RZ = ...
    CX = ...
    CZ = ...
    SWAP = ...


class ResultMode(Enum):
    SAMPLE = ...
    EXPECTATION = ...
    PROBABILITIES = ...
    VARIANCE = ...
    STATEVECTOR = ...


class Operation:
    @property
    def name(self) -> str: ...
    @property
    def code(self) -> OperationCode: ...
    @property
    def qubits(self) -> list[int]: ...
    @property
    def parameters(self) -> list[float]: ...


class ParameterSlot:
    def __init__(self, operation_index: int, parameter_index: int = 0) -> None: ...
    @property
    def operation_index(self) -> int: ...
    @property
    def parameter_index(self) -> int: ...


class Program:
    def __init__(self, num_qubits: int) -> None: ...
    @property
    def num_qubits(self) -> int: ...
    @property
    def operations(self) -> list[Operation]: ...
    @property
    def canonical_text(self) -> str: ...
    @property
    def fingerprint(self) -> str: ...
    def bind(self, slots: list[ParameterSlot], values: list[float]) -> Program: ...


class PauliZ:
    @property
    def qubit(self) -> int: ...


class Target:
    @property
    def name(self) -> str: ...
    @property
    def operations(self) -> list[OperationCode]: ...
    @property
    def result_modes(self) -> list[ResultMode]: ...
    @property
    def max_qubits(self) -> int | None: ...
    @property
    def simulator(self) -> bool: ...
    @property
    def state_access(self) -> bool: ...
    @property
    def mid_circuit_measurement(self) -> bool: ...
    @property
    def reset(self) -> bool: ...
    @property
    def dynamic_control(self) -> bool: ...
    @property
    def parameter_batches(self) -> bool: ...
    @property
    def fingerprint(self) -> str: ...
    def supports_operation(self, code: OperationCode) -> bool: ...
    def supports_result(self, mode: ResultMode) -> bool: ...


class ExecutionPlan:
    @property
    def backend(self) -> str: ...
    @property
    def method(self) -> str: ...
    @property
    def exact(self) -> bool: ...
    @property
    def threads(self) -> int: ...
    @property
    def original_operations(self) -> int: ...
    @property
    def compiled_steps(self) -> int: ...
    @property
    def active_qubits(self) -> int: ...
    @property
    def estimated_state_bytes(self) -> int: ...
    @property
    def result_mode(self) -> ResultMode: ...
    @property
    def program_fingerprint(self) -> str: ...
    @property
    def target_fingerprint(self) -> str: ...
    @property
    def cache_key(self) -> str: ...


class StateVector:
    @property
    def values(self) -> npt.NDArray[np.complex128]: ...
    @property
    def backend(self) -> str: ...


class Probabilities:
    @property
    def values(self) -> npt.NDArray[np.float64]: ...
    @property
    def backend(self) -> str: ...


class Samples:
    @property
    def values(self) -> npt.NDArray[np.int8]: ...
    @property
    def shots(self) -> int: ...
    @property
    def backend(self) -> str: ...
    def counts(self) -> dict[str, int]: ...


class SamplesBatch:
    @property
    def values(self) -> npt.NDArray[np.int8]: ...
    @property
    def batch_size(self) -> int: ...
    @property
    def shots(self) -> int: ...
    @property
    def num_qubits(self) -> int: ...
    @property
    def parameter_count(self) -> int: ...
    @property
    def backend(self) -> str: ...
    @property
    def compiled_steps(self) -> int: ...
    @property
    def estimated_state_bytes(self) -> int: ...
    def counts(self, batch_index: int) -> dict[str, int]: ...


class Expectation:
    @property
    def value(self) -> float: ...
    @property
    def backend(self) -> str: ...
    @property
    def active_qubits(self) -> int: ...
    @property
    def compiled_steps(self) -> int: ...
    @property
    def estimated_state_bytes(self) -> int: ...


class ExpectationBatch:
    @property
    def values(self) -> npt.NDArray[np.float64]: ...
    @property
    def batch_size(self) -> int: ...
    @property
    def parameter_count(self) -> int: ...
    @property
    def backend(self) -> str: ...
    @property
    def active_qubits(self) -> int: ...
    @property
    def compiled_steps(self) -> int: ...
    @property
    def estimated_state_bytes(self) -> int: ...


class Variance:
    @property
    def value(self) -> float: ...
    @property
    def backend(self) -> str: ...
    @property
    def active_qubits(self) -> int: ...
    @property
    def compiled_steps(self) -> int: ...
    @property
    def estimated_state_bytes(self) -> int: ...


def h(program: Program, qubit: int) -> Program: ...
def x(program: Program, qubit: int) -> Program: ...
def y(program: Program, qubit: int) -> Program: ...
def z(program: Program, qubit: int) -> Program: ...
def rx(program: Program, angle: float, qubit: int) -> Program: ...
def ry(program: Program, angle: float, qubit: int) -> Program: ...
def rz(program: Program, angle: float, qubit: int) -> Program: ...
def cx(program: Program, control: int, target: int) -> Program: ...
def cz(program: Program, control: int, target: int) -> Program: ...
def swap(program: Program, first: int, second: int) -> Program: ...
def Z(qubit: int) -> PauliZ: ...

def native_target() -> Target: ...
def plan(
    program: Program,
    result_mode: ResultMode,
    backend: str = "auto",
) -> ExecutionPlan: ...

def expectation_plan(
    program: Program,
    observable: PauliZ,
    backend: str = "auto",
) -> ExecutionPlan: ...

def variance_plan(
    program: Program,
    observable: PauliZ,
    backend: str = "auto",
) -> ExecutionPlan: ...

def statevector(program: Program, backend: str = "auto") -> StateVector: ...
def probabilities(program: Program, backend: str = "auto") -> Probabilities: ...
def sample(
    program: Program,
    shots: int = 1024,
    seed: int | None = None,
    backend: str = "auto",
) -> Samples: ...
def sample_batch(
    program: Program,
    slots: list[ParameterSlot],
    parameter_values: npt.NDArray[np.float64],
    shots: int = 1024,
    seed: int | None = None,
    backend: str = "auto",
) -> SamplesBatch: ...
def expect(
    program: Program,
    observable: PauliZ,
    backend: str = "auto",
) -> Expectation: ...
def expect_batch(
    program: Program,
    observable: PauliZ,
    slots: list[ParameterSlot],
    parameter_values: npt.NDArray[np.float64],
    backend: str = "auto",
) -> ExpectationBatch: ...
def variance(
    program: Program,
    observable: PauliZ,
    backend: str = "auto",
) -> Variance: ...

def core_language() -> str: ...
def core_version() -> str: ...
def ir_version() -> int: ...
def parallel_threads() -> int: ...
