from enum import Enum
from typing import overload

import numpy as np
import numpy.typing as npt

class OperationCode(Enum):
    H = ...
    X = ...
    Y = ...
    Z = ...
    RX = ...
    RY = ...
    RZ = ...
    CX = ...
    CZ = ...
    SWAP = ...


class ResultMode(Enum):
    SAMPLE = ...
    EXPECTATION = ...
    PROBABILITIES = ...
    VARIANCE = ...
    STATEVECTOR = ...


class Pauli(Enum):
    I = ...
    X = ...
    Y = ...
    Z = ...


class GradientMethod(Enum):
    AUTO = ...
    ADJOINT = ...
    PARAMETER_SHIFT = ...
    FINITE_DIFFERENCE = ...


class ProviderJobState(Enum):
    QUEUED = ...
    RUNNING = ...
    SUCCEEDED = ...
    FAILED = ...
    CANCELLED = ...


class NoiseChannelCode(Enum):
    BIT_FLIP = ...
    PHASE_FLIP = ...
    DEPOLARIZING = ...
    AMPLITUDE_DAMPING = ...
    PHASE_DAMPING = ...
    PAULI = ...
    KRAUS = ...


class CircuitOperationCode(Enum):
    H = ...
    X = ...
    Y = ...
    Z = ...
    RX = ...
    RY = ...
    RZ = ...
    CX = ...
    CZ = ...
    SWAP = ...
    MEASURE = ...
    RESET = ...
    BARRIER = ...


class Operation:
    @property
    def name(self) -> str: ...
    @property
    def code(self) -> OperationCode: ...
    @property
    def qubits(self) -> list[int]: ...
    @property
    def parameters(self) -> list[float]: ...


class ParameterSlot:
    def __init__(self, operation_index: int, parameter_index: int = 0) -> None: ...
    @property
    def operation_index(self) -> int: ...
    @property
    def parameter_index(self) -> int: ...


class Program:
    def __init__(self, num_qubits: int) -> None: ...
    @property
    def num_qubits(self) -> int: ...
    @property
    def operations(self) -> list[Operation]: ...
    @property
    def canonical_text(self) -> str: ...
    @property
    def fingerprint(self) -> str: ...
    def bind(self, slots: list[ParameterSlot], values: list[float]) -> Program: ...


class PauliZ:
    @property
    def qubit(self) -> int: ...


class PauliFactor:
    def __init__(self, qubit: int, pauli: Pauli) -> None: ...
    @property
    def qubit(self) -> int: ...
    @property
    def pauli(self) -> Pauli: ...


class PauliTerm:
    def __init__(self, coefficient: float, factors: list[PauliFactor]) -> None: ...
    @property
    def coefficient(self) -> float: ...
    @property
    def factors(self) -> list[PauliFactor]: ...
    @property
    def canonical_text(self) -> str: ...


class Observable:
    def __init__(self, terms: list[PauliTerm]) -> None: ...
    @property
    def terms(self) -> list[PauliTerm]: ...
    @property
    def canonical_text(self) -> str: ...
    @property
    def fingerprint(self) -> str: ...


class Target:
    @property
    def name(self) -> str: ...
    @property
    def operations(self) -> list[OperationCode]: ...
    @property
    def result_modes(self) -> list[ResultMode]: ...
    @property
    def max_qubits(self) -> int | None: ...
    @property
    def simulator(self) -> bool: ...
    @property
    def state_access(self) -> bool: ...
    @property
    def mid_circuit_measurement(self) -> bool: ...
    @property
    def reset(self) -> bool: ...
    @property
    def dynamic_control(self) -> bool: ...
    @property
    def parameter_batches(self) -> bool: ...
    @property
    def fingerprint(self) -> str: ...
    def supports_operation(self, code: OperationCode) -> bool: ...
    def supports_result(self, mode: ResultMode) -> bool: ...


class ExecutionPlan:
    @property
    def backend(self) -> str: ...
    @property
    def method(self) -> str: ...
    @property
    def exact(self) -> bool: ...
    @property
    def threads(self) -> int: ...
    @property
    def original_qubits(self) -> int: ...
    @property
    def original_operations(self) -> int: ...
    @property
    def active_qubits(self) -> int: ...
    @property
    def active_operations(self) -> int: ...
    @property
    def single_qubit_operations(self) -> int: ...
    @property
    def two_qubit_operations(self) -> int: ...
    @property
    def parameterized_operations(self) -> int: ...
    @property
    def non_clifford_operations(self) -> int: ...
    @property
    def compiled_steps(self) -> int: ...
    @property
    def estimated_state_bytes(self) -> int: ...
    @property
    def result_mode(self) -> ResultMode: ...
    @property
    def workload_version(self) -> int: ...
    @property
    def workload_fingerprint(self) -> str: ...
    @property
    def program_fingerprint(self) -> str: ...
    @property
    def target_fingerprint(self) -> str: ...
    @property
    def cache_key(self) -> str: ...
    @property
    def predicted_ns(self) -> float | None: ...
    @property
    def cost_model_class(self) -> str: ...
    @property
    def cost_model_fingerprint(self) -> str: ...
    @property
    def cost_model_host_fingerprint(self) -> str: ...
    @property
    def cost_model_cuda_host_fingerprint(self) -> str: ...
    @property
    def tensor_network_max_bond(self) -> int: ...
    @property
    def tensor_network_routed_swaps(self) -> int: ...
    @property
    def tensor_network_contraction_work(self) -> float: ...


class PlannerCostModel:
    @property
    def schema_version(self) -> int: ...
    @property
    def workload_version(self) -> int: ...
    @property
    def engine_version(self) -> str: ...
    @property
    def host_fingerprint(self) -> str: ...
    @property
    def cuda_host_fingerprint(self) -> str: ...
    @property
    def artifact_fingerprint(self) -> str: ...
    @property
    def cost_classes(self) -> list[str]: ...
    @property
    def cuda_auto_validated(self) -> bool: ...
    @property
    def mps_auto_validated(self) -> bool: ...
    @property
    def observable_auto_validated(self) -> bool: ...
    @property
    def density_auto_validated(self) -> bool: ...
    @property
    def mps_policy_version(self) -> int: ...
    @property
    def observable_policy_version(self) -> int: ...
    @property
    def density_policy_version(self) -> int: ...
    def predict_ns(self, plan: ExecutionPlan) -> float: ...
    def predict_density_ns(
        self,
        backend: str,
        qubits: int,
        single_qubit_operations: int,
        two_qubit_operations: int,
        noise_events: int,
        kraus_evaluations: int,
    ) -> float: ...
    def predict_density_speedup(
        self,
        qubits: int,
        single_qubit_operations: int,
        two_qubit_operations: int,
        noise_events: int,
        kraus_evaluations: int,
    ) -> float: ...

class StateVector:
    @property
    def values(self) -> npt.NDArray[np.complex128]: ...
    @property
    def backend(self) -> str: ...


class Probabilities:
    @property
    def values(self) -> npt.NDArray[np.float64]: ...
    @property
    def backend(self) -> str: ...


class Samples:
    @property
    def values(self) -> npt.NDArray[np.int8]: ...
    @property
    def shots(self) -> int: ...
    @property
    def backend(self) -> str: ...
    def counts(self) -> dict[str, int]: ...


class SamplesBatch:
    @property
    def values(self) -> npt.NDArray[np.int8]: ...
    @property
    def batch_size(self) -> int: ...
    @property
    def shots(self) -> int: ...
    @property
    def num_qubits(self) -> int: ...
    @property
    def parameter_count(self) -> int: ...
    @property
    def backend(self) -> str: ...
    @property
    def compiled_steps(self) -> int: ...
    @property
    def estimated_state_bytes(self) -> int: ...
    def counts(self, batch_index: int) -> dict[str, int]: ...


class Expectation:
    @property
    def value(self) -> float: ...
    @property
    def backend(self) -> str: ...
    @property
    def active_qubits(self) -> int: ...
    @property
    def compiled_steps(self) -> int: ...
    @property
    def estimated_state_bytes(self) -> int: ...


class ExpectationBatch:
    @property
    def values(self) -> npt.NDArray[np.float64]: ...
    @property
    def batch_size(self) -> int: ...
    @property
    def parameter_count(self) -> int: ...
    @property
    def backend(self) -> str: ...
    @property
    def active_qubits(self) -> int: ...
    @property
    def compiled_steps(self) -> int: ...
    @property
    def estimated_state_bytes(self) -> int: ...


class Variance:
    @property
    def value(self) -> float: ...
    @property
    def backend(self) -> str: ...
    @property
    def active_qubits(self) -> int: ...
    @property
    def compiled_steps(self) -> int: ...
    @property
    def estimated_state_bytes(self) -> int: ...


class ObservableExecutionPlan:
    @property
    def backend(self) -> str: ...
    @property
    def method(self) -> str: ...
    @property
    def exact(self) -> bool: ...
    @property
    def active_qubits(self) -> int: ...
    @property
    def observable_count(self) -> int: ...
    @property
    def term_count(self) -> int: ...
    @property
    def measurement_group_count(self) -> int: ...
    @property
    def estimated_state_bytes(self) -> int: ...
    @property
    def program_fingerprint(self) -> str: ...
    @property
    def query_fingerprint(self) -> str: ...
    @property
    def cache_key(self) -> str: ...
    @property
    def predicted_ns(self) -> float | None: ...
    @property
    def cost_model_class(self) -> str: ...
    @property
    def cost_model_fingerprint(self) -> str: ...

class ObservableResult:
    @property
    def value(self) -> float: ...
    @property
    def backend(self) -> str: ...
    @property
    def active_qubits(self) -> int: ...
    @property
    def evaluations(self) -> int: ...


class ObservableBatch:
    @property
    def values(self) -> npt.NDArray[np.float64]: ...
    @property
    def observable_count(self) -> int: ...
    @property
    def backend(self) -> str: ...
    @property
    def active_qubits(self) -> int: ...


class MeasurementGroup:
    @property
    def term_indices(self) -> list[int]: ...
    @property
    def basis(self) -> list[PauliFactor]: ...


class ShotEstimate:
    @property
    def value(self) -> float: ...
    @property
    def standard_error(self) -> float: ...
    @property
    def shots_per_group(self) -> int: ...
    @property
    def total_shots(self) -> int: ...
    @property
    def group_count(self) -> int: ...
    @property
    def backend(self) -> str: ...


class GradientResult:
    @property
    def value(self) -> float: ...
    @property
    def gradient(self) -> npt.NDArray[np.float64]: ...
    @property
    def method(self) -> str: ...
    @property
    def backend(self) -> str: ...
    @property
    def evaluations(self) -> int: ...


class JacobianResult:
    @property
    def values(self) -> npt.NDArray[np.float64]: ...
    @property
    def jacobian(self) -> npt.NDArray[np.float64]: ...
    @property
    def observable_count(self) -> int: ...
    @property
    def parameter_count(self) -> int: ...
    @property
    def method(self) -> str: ...
    @property
    def backend(self) -> str: ...
    @property
    def evaluations(self) -> int: ...


class HessianResult:
    @property
    def value(self) -> float: ...
    @property
    def gradient(self) -> npt.NDArray[np.float64]: ...
    @property
    def hessian(self) -> npt.NDArray[np.float64]: ...
    @property
    def parameter_count(self) -> int: ...
    @property
    def method(self) -> str: ...
    @property
    def backend(self) -> str: ...
    @property
    def evaluations(self) -> int: ...

class OptimizationReport:
    @property
    def program(self) -> Program: ...
    @property
    def original_operations(self) -> int: ...
    @property
    def optimized_operations(self) -> int: ...
    @property
    def passes(self) -> list[str]: ...


class NoiseChannel:
    @property
    def code(self) -> NoiseChannelCode: ...
    @property
    def qubit(self) -> int: ...
    @property
    def parameters(self) -> list[float]: ...
    @property
    def kraus_operators(self) -> list[complex]: ...
    @property
    def kraus_count(self) -> int: ...


class NoiseInstruction:
    def __init__(self, after_operation: int, channel: NoiseChannel) -> None: ...
    @property
    def after_operation(self) -> int: ...
    @property
    def channel(self) -> NoiseChannel: ...


class NoisyProgram:
    def __init__(self, program: Program, noise: list[NoiseInstruction]) -> None: ...
    @property
    def program(self) -> Program: ...
    @property
    def noise(self) -> list[NoiseInstruction]: ...


class DensityMatrix:
    @property
    def values(self) -> npt.NDArray[np.complex128]: ...
    @property
    def dimension(self) -> int: ...
    @property
    def backend(self) -> str: ...


class LindbladResult:
    @property
    def state(self) -> DensityMatrix: ...
    @property
    def dt(self) -> float: ...
    @property
    def steps(self) -> int: ...


class ProviderProgram:
    @property
    def format(self) -> str: ...
    @property
    def text(self) -> str: ...
    @property
    def num_qubits(self) -> int: ...
    @property
    def measures_all(self) -> bool: ...


class ProviderPlugin:
    def __init__(self, path: str) -> None: ...
    @property
    def name(self) -> str: ...
    def capabilities_json(self) -> str: ...
    def submit(
        self,
        program: ProviderProgram,
        shots: int,
        options_json: str = "{}",
    ) -> str: ...
    def poll(self, job_id: str) -> ProviderJobState: ...
    def result_json(self, job_id: str) -> str: ...
    def cancel(self, job_id: str) -> None: ...


class DetectorError:
    def __init__(
        self,
        probability: float,
        detectors: list[int],
        observables: list[int] = [],
    ) -> None: ...
    @property
    def probability(self) -> float: ...
    @property
    def detectors(self) -> list[int]: ...
    @property
    def observables(self) -> list[int]: ...


class DetectorModel:
    def __init__(
        self,
        detector_count: int,
        observable_count: int,
        errors: list[DetectorError],
    ) -> None: ...
    @property
    def detector_count(self) -> int: ...
    @property
    def observable_count(self) -> int: ...
    @property
    def errors(self) -> list[DetectorError]: ...
    @property
    def canonical_text(self) -> str: ...
    @property
    def fingerprint(self) -> str: ...


class DetectorSamples:
    @property
    def syndrome(self) -> npt.NDArray[np.int8]: ...
    @property
    def observables(self) -> npt.NDArray[np.int8]: ...
    @property
    def shots(self) -> int: ...
    @property
    def detector_count(self) -> int: ...
    @property
    def observable_count(self) -> int: ...


class DecodeResult:
    @property
    def observables(self) -> list[int]: ...
    @property
    def log_likelihood(self) -> float: ...
    @property
    def matched_errors(self) -> int: ...


class DistributedInfo:
    @property
    def available(self) -> bool: ...
    @property
    def world_size(self) -> int: ...
    @property
    def rank(self) -> int: ...
    @property
    def local_rank(self) -> int: ...
    @property
    def runtime(self) -> str: ...


class DistributedStateVector:
    @property
    def local_values(self) -> npt.NDArray[np.complex128]: ...
    @property
    def global_size(self) -> int: ...
    @property
    def global_offset(self) -> int: ...
    @property
    def rank(self) -> int: ...
    @property
    def world_size(self) -> int: ...
    @property
    def backend(self) -> str: ...


class ClassicalCondition:
    def __init__(self, bit: int, value: bool) -> None: ...
    @property
    def bit(self) -> int: ...
    @property
    def value(self) -> bool: ...


class CircuitInstruction:
    @property
    def name(self) -> str: ...
    @property
    def code(self) -> CircuitOperationCode: ...
    @property
    def qubits(self) -> list[int]: ...
    @property
    def parameters(self) -> list[float]: ...
    @property
    def classical_bits(self) -> list[int]: ...
    @property
    def condition(self) -> ClassicalCondition | None: ...


class Circuit:
    def __init__(self, num_qubits: int, num_clbits: int = 0) -> None: ...
    @property
    def num_qubits(self) -> int: ...
    @property
    def num_clbits(self) -> int: ...
    @property
    def instructions(self) -> list[CircuitInstruction]: ...
    @property
    def canonical_text(self) -> str: ...
    @property
    def fingerprint(self) -> str: ...
    def to_openqasm3(self) -> str: ...
    def to_program(self) -> Program: ...
    @staticmethod
    def from_program(program: Program, num_clbits: int = 0) -> Circuit: ...
    @staticmethod
    def from_openqasm3(text: str) -> Circuit: ...
    def h(self, qubit: int, condition: ClassicalCondition | None = None) -> Circuit: ...
    def x(self, qubit: int, condition: ClassicalCondition | None = None) -> Circuit: ...
    def y(self, qubit: int, condition: ClassicalCondition | None = None) -> Circuit: ...
    def z(self, qubit: int, condition: ClassicalCondition | None = None) -> Circuit: ...
    def rx(self, angle: float, qubit: int, condition: ClassicalCondition | None = None) -> Circuit: ...
    def ry(self, angle: float, qubit: int, condition: ClassicalCondition | None = None) -> Circuit: ...
    def rz(self, angle: float, qubit: int, condition: ClassicalCondition | None = None) -> Circuit: ...
    def cx(self, control: int, target: int, condition: ClassicalCondition | None = None) -> Circuit: ...
    def cz(self, control: int, target: int, condition: ClassicalCondition | None = None) -> Circuit: ...
    def swap(self, first: int, second: int, condition: ClassicalCondition | None = None) -> Circuit: ...
    def measure(
        self,
        qubit: int,
        classical_bit: int,
        condition: ClassicalCondition | None = None,
    ) -> Circuit: ...
    def reset(self, qubit: int, condition: ClassicalCondition | None = None) -> Circuit: ...
    def barrier(self, qubits: list[int] = ...) -> Circuit: ...


class Coupling:
    def __init__(self, first: int, second: int) -> None: ...
    @property
    def first(self) -> int: ...
    @property
    def second(self) -> int: ...


class OperationDuration:
    def __init__(self, code: CircuitOperationCode, nanoseconds: float) -> None: ...
    @property
    def code(self) -> CircuitOperationCode: ...
    @property
    def nanoseconds(self) -> float: ...


class HardwareTarget:
    def __init__(
        self,
        name: str,
        num_qubits: int,
        one_qubit_operations: list[CircuitOperationCode],
        two_qubit_operations: list[CircuitOperationCode],
        couplings: list[Coupling] = ...,
        measurement: bool = False,
        mid_circuit_measurement: bool = False,
        reset: bool = False,
        dynamic_control: bool = False,
        durations: list[OperationDuration] = ...,
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def num_qubits(self) -> int: ...
    @property
    def one_qubit_operations(self) -> list[CircuitOperationCode]: ...
    @property
    def two_qubit_operations(self) -> list[CircuitOperationCode]: ...
    @property
    def couplings(self) -> list[Coupling]: ...
    @property
    def measurement(self) -> bool: ...
    @property
    def mid_circuit_measurement(self) -> bool: ...
    @property
    def reset(self) -> bool: ...
    @property
    def dynamic_control(self) -> bool: ...
    @property
    def durations(self) -> list[OperationDuration]: ...
    def adjacent(self, first: int, second: int) -> bool: ...
    def supports(self, code: CircuitOperationCode, qubits: list[int]) -> bool: ...
    def duration_ns(self, code: CircuitOperationCode) -> float | None: ...
    @property
    def canonical_text(self) -> str: ...
    @property
    def fingerprint(self) -> str: ...


class ScheduledInstruction:
    @property
    def instruction_index(self) -> int: ...
    @property
    def start_ns(self) -> float: ...
    @property
    def duration_ns(self) -> float: ...


class CompilationResult:
    @property
    def circuit(self) -> Circuit: ...
    @property
    def initial_layout(self) -> list[int]: ...
    @property
    def final_layout(self) -> list[int]: ...
    @property
    def original_operations(self) -> int: ...
    @property
    def optimized_operations(self) -> int: ...
    @property
    def routed_operations(self) -> int: ...
    @property
    def compiled_operations(self) -> int: ...
    @property
    def inserted_swaps(self) -> int: ...
    @property
    def decompositions(self) -> int: ...
    @property
    def depth(self) -> int: ...
    @property
    def duration_ns(self) -> float | None: ...
    @property
    def schedule(self) -> list[ScheduledInstruction]: ...
    @property
    def target_fingerprint(self) -> str: ...


class BpOsdDecodeResult:
    @property
    def correction(self) -> npt.NDArray[np.int8]: ...
    @property
    def observables(self) -> npt.NDArray[np.int8]: ...
    @property
    def log_likelihood(self) -> float: ...
    @property
    def matched_errors(self) -> int: ...
    @property
    def iterations(self) -> int: ...
    @property
    def bp_converged(self) -> bool: ...
    @property
    def osd_used(self) -> bool: ...


class BpOsdDecodeBatch:
    @property
    def corrections(self) -> npt.NDArray[np.int8]: ...
    @property
    def observables(self) -> npt.NDArray[np.int8]: ...
    @property
    def log_likelihoods(self) -> npt.NDArray[np.float64]: ...
    @property
    def matched_errors(self) -> npt.NDArray[np.uint64]: ...
    @property
    def iterations(self) -> npt.NDArray[np.uint64]: ...
    @property
    def bp_converged(self) -> npt.NDArray[np.int8]: ...
    @property
    def osd_used(self) -> npt.NDArray[np.int8]: ...
    @property
    def shots(self) -> int: ...
    @property
    def error_count(self) -> int: ...
    @property
    def observable_count(self) -> int: ...


class BpOsdDecoder:
    def __init__(
        self,
        model: DetectorModel,
        max_iterations: int = 50,
        damping: float = 0.0,
    ) -> None: ...
    @property
    def model(self) -> DetectorModel: ...
    @property
    def max_iterations(self) -> int: ...
    @property
    def damping(self) -> float: ...
    @property
    def edge_count(self) -> int: ...
    @property
    def active_error_count(self) -> int: ...
    def decode(self, syndrome: npt.NDArray[np.int8]) -> BpOsdDecodeResult: ...
    def decode_batch(self, syndromes: npt.NDArray[np.int8]) -> BpOsdDecodeBatch: ...


class TensorNetworkCostModel:
    @property
    def schema_version(self) -> int: ...
    @property
    def policy_version(self) -> int: ...
    @property
    def workload_version(self) -> int: ...
    @property
    def engine_version(self) -> str: ...
    @property
    def host_fingerprint(self) -> str: ...
    @property
    def artifact_fingerprint(self) -> str: ...
    @property
    def report_count(self) -> int: ...
    @property
    def decision_samples(self) -> int: ...
    @property
    def decision_mistakes(self) -> int: ...
    @property
    def decision_max_regret(self) -> float: ...
    @property
    def cpu_wins(self) -> int: ...
    @property
    def tensor_network_wins(self) -> int: ...
    @property
    def auto_validated(self) -> bool: ...
    def predict_cpu_ns(
        self,
        active_qubits: int,
        compiled_steps: int,
        two_qubit_operations: int,
        operation_count: int,
        term_count: int,
        threads: int,
    ) -> float: ...
    def predict_tensor_network_ns(
        self,
        contractions: int,
        peak_tensor_rank: int,
        peak_tensor_bytes: int,
        scalar_multiplications: float,
        term_count: int,
    ) -> float: ...


class TensorNetworkPlan:
    @property
    def term_count(self) -> int: ...
    @property
    def contractions(self) -> int: ...
    @property
    def peak_tensor_rank(self) -> int: ...
    @property
    def peak_tensor_bytes(self) -> int: ...
    @property
    def scalar_multiplications(self) -> float: ...
    @property
    def max_tensor_bytes(self) -> int: ...
    @property
    def exact(self) -> bool: ...
    @property
    def backend(self) -> str: ...
    @property
    def method(self) -> str: ...
    @property
    def program_fingerprint(self) -> str: ...
    @property
    def observable_fingerprint(self) -> str: ...
    @property
    def plan_fingerprint(self) -> str: ...


class TensorNetworkResult:
    @property
    def value(self) -> float: ...
    @property
    def term_count(self) -> int: ...
    @property
    def contractions(self) -> int: ...
    @property
    def peak_tensor_rank(self) -> int: ...
    @property
    def peak_tensor_bytes(self) -> int: ...
    @property
    def scalar_multiplications(self) -> float: ...
    @property
    def exact(self) -> bool: ...
    @property
    def backend(self) -> str: ...
    @property
    def method(self) -> str: ...


class TrajectoryBatch:
    @property
    def values(self) -> npt.NDArray[np.float64]: ...
    @property
    def standard_errors(self) -> npt.NDArray[np.float64]: ...
    @property
    def observable_count(self) -> int: ...
    @property
    def trajectories(self) -> int: ...
    @property
    def seed(self) -> int: ...
    @property
    def state_bytes(self) -> int: ...
    @property
    def exact(self) -> bool: ...
    @property
    def backend(self) -> str: ...
    @property
    def method(self) -> str: ...


class DistributedTensorNetworkResult:
    @property
    def value(self) -> float: ...
    @property
    def term_count(self) -> int: ...
    @property
    def contractions(self) -> int: ...
    @property
    def peak_tensor_rank(self) -> int: ...
    @property
    def peak_tensor_bytes(self) -> int: ...
    @property
    def scalar_multiplications(self) -> float: ...
    @property
    def world_size(self) -> int: ...
    @property
    def active_ranks(self) -> int: ...
    @property
    def exact(self) -> bool: ...
    @property
    def backend(self) -> str: ...
    @property
    def method(self) -> str: ...


class DistributedTrajectoryBatch:
    @property
    def values(self) -> npt.NDArray[np.float64]: ...
    @property
    def standard_errors(self) -> npt.NDArray[np.float64]: ...
    @property
    def observable_count(self) -> int: ...
    @property
    def trajectories(self) -> int: ...
    @property
    def seed(self) -> int: ...
    @property
    def state_bytes_per_rank(self) -> int: ...
    @property
    def world_size(self) -> int: ...
    @property
    def active_ranks(self) -> int: ...
    @property
    def exact(self) -> bool: ...
    @property
    def backend(self) -> str: ...
    @property
    def method(self) -> str: ...


def circuit_ir_version() -> int: ...
def compile_circuit(
    circuit: Circuit,
    target: HardwareTarget,
    initial_layout: list[int] = ...,
    optimization_level: int = 1,
) -> CompilationResult: ...
def decode_detector_model_bp_osd(
    model: DetectorModel,
    syndrome: npt.NDArray[np.int8],
    max_iterations: int = 50,
    damping: float = 0.0,
) -> BpOsdDecodeResult: ...
def load_tensor_network_cost_model(path: str) -> TensorNetworkCostModel: ...
def tensor_network_plan(
    program: Program,
    observable: Observable,
    max_tensor_bytes: int = ...,
) -> TensorNetworkPlan: ...
def tensor_network_expectation(
    program: Program,
    observable: Observable,
    max_tensor_bytes: int = ...,
) -> TensorNetworkResult: ...
def tensor_network_observable_plan(
    program: Program,
    observables: list[Observable],
    max_tensor_bytes: int = ...,
) -> ObservableExecutionPlan: ...
def tensor_network_auto_observable_plan(
    program: Program,
    observables: list[Observable],
    cost_model: TensorNetworkCostModel,
    max_tensor_bytes: int = ...,
) -> ObservableExecutionPlan: ...
def tensor_network_expect_observable(
    program: Program,
    observable: Observable,
    max_tensor_bytes: int = ...,
) -> ObservableResult: ...
def tensor_network_expect_observables(
    program: Program,
    observables: list[Observable],
    max_tensor_bytes: int = ...,
) -> ObservableBatch: ...
def trajectory_expectations(
    program: NoisyProgram,
    observables: list[Observable],
    trajectories: int,
    seed: int | None = None,
    backend: str = "auto",
) -> TrajectoryBatch: ...
def distributed_tensor_network_expectation(
    program: Program,
    observable: Observable,
    max_tensor_bytes: int = ...,
) -> DistributedTensorNetworkResult: ...
def distributed_trajectory_expectations(
    program: NoisyProgram,
    observables: list[Observable],
    trajectories: int,
    seed: int | None = None,
) -> DistributedTrajectoryBatch: ...


def h(program: Program, qubit: int) -> Program: ...
def x(program: Program, qubit: int) -> Program: ...
def y(program: Program, qubit: int) -> Program: ...
def z(program: Program, qubit: int) -> Program: ...
def rx(program: Program, angle: float, qubit: int) -> Program: ...
def ry(program: Program, angle: float, qubit: int) -> Program: ...
def rz(program: Program, angle: float, qubit: int) -> Program: ...
def cx(program: Program, control: int, target: int) -> Program: ...
def cz(program: Program, control: int, target: int) -> Program: ...
def swap(program: Program, first: int, second: int) -> Program: ...
def Z(qubit: int) -> PauliZ: ...
def pauli(qubit: int, value: Pauli) -> PauliFactor: ...
def pauli_term(coefficient: float, factors: list[PauliFactor]) -> PauliTerm: ...
def observable(terms: list[PauliTerm]) -> Observable: ...
def observable_from_z(observable: PauliZ) -> Observable: ...
def observable_plan(
    program: Program,
    observables: list[Observable],
    backend: str = "auto",
    cost_model: PlannerCostModel | None = None,
) -> ObservableExecutionPlan: ...
def commuting_groups(observable: Observable) -> list[list[int]]: ...
def measurement_groups(observable: Observable) -> list[MeasurementGroup]: ...
def estimate_observable(
    program: Program,
    observable: Observable,
    shots_per_group: int = 1024,
    seed: int | None = None,
    backend: str = "auto",
) -> ShotEstimate: ...
def expect_observable(
    program: Program,
    observable: Observable,
    backend: str = "auto",
) -> ObservableResult: ...
def variance_observable(
    program: Program,
    observable: Observable,
    backend: str = "auto",
) -> ObservableResult: ...
def covariance(
    program: Program,
    left: Observable,
    right: Observable,
    backend: str = "auto",
) -> ObservableResult: ...
def expect_observables(
    program: Program,
    observables: list[Observable],
    backend: str = "auto",
) -> ObservableBatch: ...

def native_target() -> Target: ...
def cuda_available() -> bool: ...
def cuda_unavailable_reason() -> str: ...
def cuda_device_name() -> str: ...
def cuda_target() -> Target: ...
def mps_target() -> Target: ...
def adaptive_mps_target() -> Target: ...
def planner_host_fingerprint() -> str: ...
def planner_cuda_host_fingerprint() -> str: ...
def load_planner_cost_model(path: str) -> PlannerCostModel: ...
def plan(
    program: Program,
    result_mode: ResultMode,
    backend: str = "auto",
    cost_model: PlannerCostModel | None = None,
) -> ExecutionPlan: ...

def expectation_plan(
    program: Program,
    observable: PauliZ,
    backend: str = "auto",
    cost_model: PlannerCostModel | None = None,
) -> ExecutionPlan: ...

def variance_plan(
    program: Program,
    observable: PauliZ,
    backend: str = "auto",
    cost_model: PlannerCostModel | None = None,
) -> ExecutionPlan: ...

def statevector(
    program: Program,
    backend: str = "auto",
    cost_model: PlannerCostModel | None = None,
) -> StateVector: ...
def probabilities(program: Program, backend: str = "auto") -> Probabilities: ...
def sample(
    program: Program,
    shots: int = 1024,
    seed: int | None = None,
    backend: str = "auto",
) -> Samples: ...
def sample_batch(
    program: Program,
    slots: list[ParameterSlot],
    parameter_values: npt.NDArray[np.float64],
    shots: int = 1024,
    seed: int | None = None,
    backend: str = "auto",
) -> SamplesBatch: ...
@overload
def expect(
    program: Program,
    observable: PauliZ,
    backend: str = "auto",
    cost_model: PlannerCostModel | None = None,
) -> Expectation: ...
@overload
def expect(
    program: Program,
    observable: Observable,
    backend: str = "auto",
) -> ObservableResult: ...
def expect_batch(
    program: Program,
    observable: PauliZ,
    slots: list[ParameterSlot],
    parameter_values: npt.NDArray[np.float64],
    backend: str = "auto",
) -> ExpectationBatch: ...
@overload
def variance(
    program: Program,
    observable: PauliZ,
    backend: str = "auto",
    cost_model: PlannerCostModel | None = None,
) -> Variance: ...
@overload
def variance(
    program: Program,
    observable: Observable,
    backend: str = "auto",
) -> ObservableResult: ...

def value_and_grad(
    program: Program,
    observable: Observable,
    slots: list[ParameterSlot],
    parameter_values: npt.NDArray[np.float64],
    backend: str = "auto",
    method: GradientMethod = GradientMethod.AUTO,
    epsilon: float = 1e-7,
) -> GradientResult: ...
def grad(
    program: Program,
    observable: Observable,
    slots: list[ParameterSlot],
    parameter_values: npt.NDArray[np.float64],
    backend: str = "auto",
    method: GradientMethod = GradientMethod.AUTO,
    epsilon: float = 1e-7,
) -> GradientResult: ...
def jacobian(
    program: Program,
    observables: list[Observable],
    slots: list[ParameterSlot],
    parameter_values: npt.NDArray[np.float64],
    backend: str = "auto",
    method: GradientMethod = GradientMethod.AUTO,
    epsilon: float = 1e-7,
) -> JacobianResult: ...
def hessian(
    program: Program,
    observable: Observable,
    slots: list[ParameterSlot],
    parameter_values: npt.NDArray[np.float64],
    backend: str = "auto",
) -> HessianResult: ...
def optimize(program: Program, level: int = 2) -> OptimizationReport: ...
def bit_flip(qubit: int, probability: float) -> NoiseChannel: ...
def phase_flip(qubit: int, probability: float) -> NoiseChannel: ...
def depolarizing(qubit: int, probability: float) -> NoiseChannel: ...
def amplitude_damping(qubit: int, gamma: float) -> NoiseChannel: ...
def phase_damping(qubit: int, gamma: float) -> NoiseChannel: ...
def pauli_channel(
    qubit: int,
    probability_x: float,
    probability_y: float,
    probability_z: float,
) -> NoiseChannel: ...
def kraus_channel(
    qubit: int,
    operators: list[npt.NDArray[np.complex128]],
) -> NoiseChannel: ...
@overload
def density_matrix(
    program: Program,
    backend: str = "auto",
    cost_model: PlannerCostModel | None = None,
) -> DensityMatrix: ...
@overload
def density_matrix(
    program: NoisyProgram,
    backend: str = "auto",
    cost_model: PlannerCostModel | None = None,
) -> DensityMatrix: ...
def lindblad_evolve(
    initial: DensityMatrix,
    hamiltonian: npt.NDArray[np.complex128],
    collapse_operators: list[npt.NDArray[np.complex128]],
    dt: float,
    steps: int,
) -> LindbladResult: ...

def to_openqasm3(program: Program, measure_all: bool = False) -> ProviderProgram: ...
def to_qir_base_profile(program: Program, measure_all: bool = True) -> ProviderProgram: ...
def repetition_code_detector_model(
    distance: int,
    rounds: int,
    data_error_probability: float,
    measurement_error_probability: float,
) -> DetectorModel: ...
def sample_detector_model(
    model: DetectorModel,
    shots: int,
    seed: int | None = None,
) -> DetectorSamples: ...
def decode_detector_model(
    model: DetectorModel,
    syndrome: npt.NDArray[np.int8],
) -> DecodeResult: ...
def distributed_info() -> DistributedInfo: ...
def mpi_compiled() -> bool: ...
def distributed_statevector(program: Program) -> DistributedStateVector: ...

def core_language() -> str: ...
def core_version() -> str: ...
def ir_version() -> int: ...
def parallel_threads() -> int: ...
