from enum import Enum

from ._native import Program

class CircuitOperationCode(Enum):
    H = ...
    X = ...
    Y = ...
    Z = ...
    RX = ...
    RY = ...
    RZ = ...
    CX = ...
    CZ = ...
    SWAP = ...
    MEASURE = ...
    RESET = ...
    BARRIER = ...


class ClassicalCondition:
    def __init__(self, bit: int, value: bool) -> None: ...
    @property
    def bit(self) -> int: ...
    @property
    def value(self) -> bool: ...


class CircuitInstruction:
    @property
    def name(self) -> str: ...
    @property
    def code(self) -> CircuitOperationCode: ...
    @property
    def qubits(self) -> list[int]: ...
    @property
    def parameters(self) -> list[float]: ...
    @property
    def classical_bits(self) -> list[int]: ...
    @property
    def condition(self) -> ClassicalCondition | None: ...


class Circuit:
    def __init__(self, num_qubits: int, num_clbits: int = 0) -> None: ...
    @property
    def num_qubits(self) -> int: ...
    @property
    def num_clbits(self) -> int: ...
    @property
    def instructions(self) -> list[CircuitInstruction]: ...
    @property
    def canonical_text(self) -> str: ...
    @property
    def fingerprint(self) -> str: ...
    def to_openqasm3(self) -> str: ...
    def to_program(self) -> Program: ...
    @staticmethod
    def from_program(program: Program, num_clbits: int = 0) -> Circuit: ...
    @staticmethod
    def from_openqasm3(text: str) -> Circuit: ...
    def h(self, qubit: int, condition: ClassicalCondition | None = None) -> Circuit: ...
    def x(self, qubit: int, condition: ClassicalCondition | None = None) -> Circuit: ...
    def y(self, qubit: int, condition: ClassicalCondition | None = None) -> Circuit: ...
    def z(self, qubit: int, condition: ClassicalCondition | None = None) -> Circuit: ...
    def rx(
        self,
        angle: float,
        qubit: int,
        condition: ClassicalCondition | None = None,
    ) -> Circuit: ...
    def ry(
        self,
        angle: float,
        qubit: int,
        condition: ClassicalCondition | None = None,
    ) -> Circuit: ...
    def rz(
        self,
        angle: float,
        qubit: int,
        condition: ClassicalCondition | None = None,
    ) -> Circuit: ...
    def cx(
        self,
        control: int,
        target: int,
        condition: ClassicalCondition | None = None,
    ) -> Circuit: ...
    def cz(
        self,
        control: int,
        target: int,
        condition: ClassicalCondition | None = None,
    ) -> Circuit: ...
    def swap(
        self,
        first: int,
        second: int,
        condition: ClassicalCondition | None = None,
    ) -> Circuit: ...
    def measure(
        self,
        qubit: int,
        classical_bit: int,
        condition: ClassicalCondition | None = None,
    ) -> Circuit: ...
    def reset(
        self,
        qubit: int,
        condition: ClassicalCondition | None = None,
    ) -> Circuit: ...
    def barrier(self, qubits: list[int] = ...) -> Circuit: ...


def circuit_ir_version() -> int: ...
