from .circuit import Circuit, CircuitOperationCode

class Coupling:
    def __init__(self, first: int, second: int) -> None: ...
    @property
    def first(self) -> int: ...
    @property
    def second(self) -> int: ...


class OperationDuration:
    def __init__(self, code: CircuitOperationCode, nanoseconds: float) -> None: ...
    @property
    def code(self) -> CircuitOperationCode: ...
    @property
    def nanoseconds(self) -> float: ...


class HardwareTarget:
    def __init__(
        self,
        name: str,
        num_qubits: int,
        one_qubit_operations: list[CircuitOperationCode],
        two_qubit_operations: list[CircuitOperationCode],
        couplings: list[Coupling] = ...,
        measurement: bool = False,
        mid_circuit_measurement: bool = False,
        reset: bool = False,
        dynamic_control: bool = False,
        durations: list[OperationDuration] = ...,
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def num_qubits(self) -> int: ...
    @property
    def one_qubit_operations(self) -> list[CircuitOperationCode]: ...
    @property
    def two_qubit_operations(self) -> list[CircuitOperationCode]: ...
    @property
    def couplings(self) -> list[Coupling]: ...
    @property
    def measurement(self) -> bool: ...
    @property
    def mid_circuit_measurement(self) -> bool: ...
    @property
    def reset(self) -> bool: ...
    @property
    def dynamic_control(self) -> bool: ...
    @property
    def durations(self) -> list[OperationDuration]: ...
    @property
    def canonical_text(self) -> str: ...
    @property
    def fingerprint(self) -> str: ...
    def adjacent(self, first: int, second: int) -> bool: ...
    def supports(self, code: CircuitOperationCode, qubits: list[int]) -> bool: ...
    def duration_ns(self, code: CircuitOperationCode) -> float | None: ...


class ScheduledInstruction:
    @property
    def instruction_index(self) -> int: ...
    @property
    def start_ns(self) -> float: ...
    @property
    def duration_ns(self) -> float: ...


class CompilationResult:
    @property
    def circuit(self) -> Circuit: ...
    @property
    def initial_layout(self) -> list[int]: ...
    @property
    def final_layout(self) -> list[int]: ...
    @property
    def original_operations(self) -> int: ...
    @property
    def optimized_operations(self) -> int: ...
    @property
    def routed_operations(self) -> int: ...
    @property
    def compiled_operations(self) -> int: ...
    @property
    def inserted_swaps(self) -> int: ...
    @property
    def decompositions(self) -> int: ...
    @property
    def depth(self) -> int: ...
    @property
    def duration_ns(self) -> float | None: ...
    @property
    def schedule(self) -> list[ScheduledInstruction]: ...
    @property
    def target_fingerprint(self) -> str: ...


def compile_circuit(
    circuit: Circuit,
    target: HardwareTarget,
    initial_layout: list[int] = ...,
    optimization_level: int = 1,
) -> CompilationResult: ...


def compile(
    circuit: Circuit,
    target: HardwareTarget,
    initial_layout: list[int] = ...,
    optimization_level: int = 1,
) -> CompilationResult: ...
